// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frectvfwnsidvdrcsryp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZWN0dmZ3bnNpZHZkcmNzcnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODM1ODgsImV4cCI6MjA2NDE1OTU4OH0._716mlJIWav8k6QQV8OscZLKMZzSud9Yg_LAJC1irz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);